server:
  port: 8085

spring:
  application:
    name: api-gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Example route config (to be customized per service)
spring:
  cloud:
    gateway:
      routes:
        - id: job-service
          uri: lb://job-service
          predicates:
            - Path=/jobs/**
        - id: company-service
          uri: lb://company-service
          predicates:
            - Path=/companies/**
        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=/reviews/** 