server:
  port: 8084

spring:
  application:
    name: review-service
  datasource:
    url: jdbc:postgresql://localhost:5000/jobber
    username: postgres
    password: mysql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

zipkin:
  base-url: http://localhost:9411/

management:
  tracing:
    enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  config:
    import: optional:configserver:http://localhost:8888 